### ISSUE TITLE
Returning '304 not modified' takes longer than returning resources

### ISSUE THREAD

**Issue by joostvanhassel** [aspnet/StaticFiles#143] opened 2016-07-05 20:16 UTC
Steps to reproduce:

- create a new website from the full template (which contains some static content)
- run
- open dev tools
- look at loading times of resources with cache `enabled`
- look at loading times of resources with cache `disabled`

(repeat last two steps several times for good measurement)

It appears returning `304 not modified` (in first scenario) takes more time than returning the full static files (in second scenario). Of course bandwith is in our favor as we run locally, but still I would expect the server to return faster if resources are not modified.

**Comment by muratg** [comment] 2016-07-25 21:58
Assigning to @pakrym for investigation

**Comment by pakrym** [comment] 2016-08-08 15:27
This is caused by console and debug loggers adding an overhead to request time. If you increase their levels to `Error` you should see `304` being faster then `200`. To increase levels change `"Microsoft": "Information"` line in `appsettings.json` to `"Microsoft": "Error"` and `loggerFactory.AddDebug();` line in `Startup.cs` to `loggerFactory.AddDebug(LogLevel.Error);`

__Test results (200):__
```
 D:\temp\Apache24\bin\ab -k -c 5 -n 50000 http://localhost:5000/images/banner1.svg
This is ApacheBench, Version 2.3 <$Revision: 1748469 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Server Software:        Kestrel
Server Hostname:        localhost
Server Port:            5000

Document Path:          /images/banner1.svg
Document Length:        9679 bytes

Concurrency Level:      5
Time taken for tests:   5.668 seconds
Complete requests:      50000
Failed requests:        0
Keep-Alive requests:    50000
Total transferred:      496000000 bytes
HTML transferred:       483950000 bytes
Requests per second:    8820.85 [#/sec] (mean)
Time per request:       0.567 [ms] (mean)
Time per request:       0.113 [ms] (mean, across all concurrent requests)
Transfer rate:          85452.03 [Kbytes/sec] received
```

__Test results (304):__
``` 
D:\temp\Apache24\bin\ab -k -c 5 -n 50000 -H "If-None-Match:1d1bd0d3b71c2cf" -H "If-Modified-Since:Thu, 02 Jun 2016 20:27:50 GMT" http://localhost:5000/images/banner1.svg
This is ApacheBench, Version 2.3 <$Revision: 1748469 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Server Software:        Kestrel
Server Hostname:        localhost
Server Port:            5000

Document Path:          /images/banner1.svg
Document Length:        0 bytes

Concurrency Level:      5
Time taken for tests:   3.082 seconds
Complete requests:      50000
Failed requests:        0
Non-2xx responses:      50000
Keep-Alive requests:    50000
Total transferred:      11450000 bytes
HTML transferred:       0 bytes
Requests per second:    16222.87 [#/sec] (mean)
Time per request:       0.308 [ms] (mean)
Time per request:       0.062 [ms] (mean, across all concurrent requests)
Transfer rate:          3627.97 [Kbytes/sec] received
```

**Closed** 2016-08-09 18:35 UTC
Labels: 3 - Done, perf
